"""add key_preview to provisioned_keys

Revision ID: c680c026a7e6
Revises: 513a5fab1fd0
Create Date: 2026-03-01 12:53:34.302177
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c680c026a7e6"
down_revision: str | None = "513a5fab1fd0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("provisioned_keys", sa.Column("key_preview", sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("provisioned_keys", "key_preview")
    # ### end Alembic commands ###
